name: assignment9
channels:
  - conda-forge
  - defaults
dependencies:
  - nbconvert=6.4.5
  - python=3.10.2
  - ipython=8.1.1
  - numpy=1.22.2
  - seaborn=0.11.2
  - py-opencv=4.5.5
  - scikit-image=0.19.2
  - pandas=1.4.1
